mensagem=Configuracao DEV vinda do GIT

#  configuração da aplicação principal
quarkus.default.datasource.db-kind=postgresql
quarkus.default.datasource.username=postgres
quarkus.default.datasource.password=postgres
quarkus.default.datasource.jdbc.url=jdbc:postgresql://localhost:5432/order_db
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
