mensagem=Configuracao DEV vinda do GIT

#  configuração da aplicação principal
quarkus.datasource.<default>.db-kind=postgresql
quarkus.datasource.<default>.username=postgres
quarkus.datasource.<default>.password=postgres
quarkus.datasource..<default>jdbc.url=jdbc:postgresql://localhost:5432/order_db
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
